name: OCaml CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: '4.14.2'  

      - name: Install dependencies
        run: opam install . --deps-only --with-doc --with-test

      - name: Check formatting with ocamlformat
        run: |
          ocamlformat --check $(find . -name '*.ml' -o -name '*.mli')

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: '4.14.2'  

      - name: Install dependencies
        run: opam install . --deps-only --with-doc --with-test

      - name: Build the project
        run: dune build @all

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: '4.14.2'  

      - name: Install dependencies
        run: opam install . --deps-only --with-doc --with-test

      - name: Run tests
        run: dune runtest